### ISSUE TITLE
Crash when generating captcha.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Edi.Captcha.AspNetCore#32]
https://github.com/EdiWang/Edi.Captcha.AspNetCore/blob/605e473666981b36b1a203fe862b87f1940e4bbe/src/Edi.Captcha/SessionBasedCaptcha.cs#L25

fail: MoongladePure.Web.Pages.ErrorModel[0]
      Error: Value cannot be null. (Parameter 'source'), client IP: 192.168.50.187, request id: 00-ca54f09d4ebac770e57b076fcf3d4390-2782c7aef98f987c-00
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentNullException: Value cannot be null. (Parameter 'source')
         at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
         at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
         at Edi.Captcha.SessionBasedCaptcha.GenerateCaptchaImageBytes(ISession httpSession, Int32 width, Int32 height, String sessionKeyName)
         at Edi.Captcha.CaptchaImageMiddleware.Invoke(HttpContext context, ISessionBasedCaptcha captcha)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: MoongladePure.Web.Pages.ErrorModel[0]
      Error: Value cannot be null. (Parameter 'source'), client IP: 192.168.50.187, request id: 00-9c82b9db0ade8b7f1399cd785e3e5f1b-3d39c10d6c9c137b-00

This happens on version: 3.23.0

3.22.0 is fine.

**Comment by Anduin2017** [comment]
This issue might be brought by: 605e473666981b36b1a203fe862b87f1940e4bbe
